stages:
- base-build
- build
- deploy

workflow:
  rules:
  - if: $CI_COMMIT_TAG
    variables:
      STAGE: production
      IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      LATEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
      BUILD_VERSION: $CI_COMMIT_TAG
  - if: $CI_COMMIT_BRANCH == "main"
    variables:
      STAGE: development
      IMAGE_TAG: $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}.${CI_COMMIT_SHORT_SHA}
      LATEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
      BUILD_VERSION: ${CI_COMMIT_REF_SLUG}.${CI_COMMIT_SHORT_SHA}
  - when: never

build:
  stage: build
  tags:
  - supermm4
  environment:
    name: $STAGE
  before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
  - |
    docker buildx build -f Dockerfile --provenance=false --platform=linux/amd64 --pull \
    --build-arg "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE" \
    --build-arg "BUILD_VERSION=$BUILD_VERSION" \
    --build-arg "NODE_ENV=$CI_ENVIRONMENT_NAME" \
    --cache-from=type=registry,ref=$IMAGE_TAG \
    --cache-to=type=inline \
    -t "$IMAGE_TAG" -t "$LATEST_IMAGE_TAG" --push .
  after_script:
  - docker rmi "$IMAGE_TAG" "$LATEST_IMAGE_TAG" || true
  rules:
  - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "main"

# deploy:
#   stage: deploy
#   environment:
#     name: $STAGE
#   variables:
#     GIT_STRATEGY: none
#   script:
#   - echo "$KUBECONFIG" | base64 -d > kubeconfig
#   - kubectl --kubeconfig=$(pwd)/kubeconfig create secret generic persis-mobile --from-env-file=${ENV}
#   - kubectl --kubeconfig=$(pwd)/kubeconfig set image deployment/${DEPLOYMENT_NAME} app=$IMAGE_TAG
#   - kubectl --kubeconfig=$(pwd)/kubeconfig rollout status deployment/${DEPLOYMENT_NAME}
#   - kubectl --kubeconfig=$(pwd)/kubeconfig describe deployment/${DEPLOYMENT_NAME}
#   rules:
#   - if: $CI_COMMIT_TAG
